/** Short lists to jog memory — not exhaustive; users can type anything. */

/** Banks & fintech + many well-known brands (Plaid, Visa, …) — quick-add only; DB rows need real claim URLs from the scraper. */

export const SUGGEST_BREACH = [
  "LinkedIn",
  "Adobe",
  "Equifax",
  "Yahoo",
  "Facebook",
  "MyFitnessPal",
  "T-Mobile",
];

export const SUGGEST_SUBSCRIPTIONS = [
  "Netflix",
  "Spotify",
  "Hulu",
  "Amazon Prime",
  "Disney+",
  "HBO Max",
  "Apple Music",
  "YouTube Premium",
  "Google Play Store",
  "Microsoft 365",
  "Adobe Creative Cloud",
  "Dropbox",
  "iCloud",
  "Xbox Game Pass",
  "PlayStation Plus",
  "ChatGPT",
];

export const SUGGEST_FINANCIAL = [
  "Chase",
  "Bank of America",
  "Wells Fargo",
  "Citi",
  "Citibank",
  "Capital One",
  "American Express",
  "PayPal",
  "Venmo",
  "Zelle",
  "Equifax",
  "Experian",
  "TransUnion",
  "Fidelity",
  "Vanguard",
  "Robinhood",
  "Coinbase",
  "Plaid",
  "Visa",
  "Mastercard",
  "Affirm",
  "Kraken",
  "Gemini",
  "Binance.US",
  "Crypto.com",
];

/** Insurance, portals, hospitals, health apps — HIPAA-adjacent; users can type anything. */
export const SUGGEST_MEDICAL = [
  "UnitedHealthcare",
  "Anthem",
  "Blue Cross",
  "Aetna",
  "Cigna",
  "Humana",
  "Kaiser",
  "MyChart",
  "Epic",
  "Cerner",
  "CVS Caremark",
  "Walgreens",
  "GoodRx",
  "Samsung Health",
  "Apple Health",
  "Google Fit",
  "MyFitnessPal",
  "Fitbit",
  "Oura",
  "Whoop",
  "Sleep Number",
  "23andMe",
];

export const SUGGEST_EMPLOYERS = [
  "Amazon",
  "Walmart",
  "Target",
  "FedEx",
  "UPS",
  "Starbucks",
  "McDonald's",
  "Uber",
  "Lyft",
  "DoorDash",
  "Instacart",
];

export const SUGGEST_RETAIL_AND_BRANDS = [
  "Amazon",
  "Walmart",
  "Target",
  "Costco",
  "Home Depot",
  "Best Buy",
  "eBay",
  "Bumble",
  "JUUL",
  "Yahoo",
  "Instagram",
  "Airbnb",
  "Tinder",
  "ChatGPT",
  "OpenAI",
  "T-Mobile",
  "Verizon",
  "AT&T",
  "Google",
  "Meta",
  "Apple",
  "Samsung",
  "Microsoft",
  "Nike",
  "Adidas",
];

export const SUGGEST_PRODUCTS = [
  "iPhone",
  "Samsung Galaxy",
  "AirPods",
  "RevitaLash",
  "Whirlpool",
  "LG",
];
